version: '2'

services:
  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "myapp.app:create_app()"
    environment: 
      PYTHONBUFFERED: 'true'
      FLASK_ENV: 'development'
    volumes:
      - '.:/myapp'
    ports:
      - '8000:8000'
